FROM rabbitmq:3.13-management

# Tải plugin delayed message exchange cho bản 3.13
ADD --chown=rabbitmq:rabbitmq https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez /plugins/

# Cấp quyền đọc cho file plugin và kích hoạt
RUN chmod 644 /plugins/rabbitmq_delayed_message_exchange-3.13.0.ez \
    && rabbitmq-plugins enable rabbitmq_delayed_message_exchange
