CREATE TYPE order_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED');
CREATE TYPE payment_type AS ENUM ('DEPOSIT');
CREATE TYPE status_transaction AS ENUM ('SUCCESS', 'FAILED', 'PENDING', 'CANCELLED');
CREATE TYPE payout_status AS ENUM ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED');
CREATE TYPE transaction_type AS ENUM ('DEPOSIT', 'BUY_COURSE', 'SELL_COURSE', 'REFUND', 'AWARD', 'WITHDRAW', 'PAYOUT');
CREATE TYPE oj_verdict AS ENUM ('PENDING', 'PROCESSING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED', 'RUNTIME_ERROR', 'COMPILATION_ERROR', 'INTERNAL_ERROR');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'LOCKED');
